### ISSUE TITLE
Consider push-based design of interact server

### ISSUE THREAD

**Issue by papajohn** [data-8/nbpuller#29]
git pulls are slow and sometimes fail. @yuvipanda suggested that we consider redesigning this component.

**Comment by SaladRaider** [comment]
@tonyyanga came up with this one possible solution:

To make nbinteract work faster and less error-prone. The idea is to just download files from github use the github api without any version control.

This way students won't have to download the whole git repository and there will be less issues since we won't have to deal with version control.

**Comment by papajohn** [comment]
We do use the merging feature of git quite regularly in order to update released student assignments with new tests and instructions (without affecting their work so far).

**Comment by yuvipanda** [comment]
Yes, we should continue using git probably, but I just want to get git
subprocess calls out of the 'main flow' (ie what happens when the student
clicks an interact link). However, since we can't / won't do much change
until next semester anyway, and I'm a little swamped right now - I'll come
back to this next month (April!).

Thanks!

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
